# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 1
    open-pull-requests-limit: 999
    groups:
      artifacts:
        patterns:
          - 'actions/*-artifact'
      caches:
        patterns:
          - 'actions/cache'
          - 'actions/cache/*'
      ci-cd:
        patterns:
          - 'changesets/*'
          - 'dependabot/*'
          - 'actions/create-github-app-token'
          - 'actions/github-script'
          - 'cloudflare/wrangler-action'
      sast:
        patterns:
          - 'github/codeql-*'
          - 'actions/dependency-review-action'
          - 'step-security/*'
          - 'microsoft/security-devops-action'
          - 'microsoft/DevSkim-Action'
          - 'ossf/*'
      setup:
        patterns:
          - 'actions/checkout'
          - 'actions/setup-*'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 1
      semver-major-days: 30
    versioning-strategy: increase
    open-pull-requests-limit: 999
    ignore:
      # 7.0.x doesn't have the stable native API yet; that's slated for 7.1 (ts-eslint needs it)
      - dependency-name: 'typescript'
        versions:
          - '>=7.0.0, <7.1.0'
    groups:
      code-management:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
          - '@demosjarco/prettier-config'
          - 'eslint'
          - 'eslint-plugin-*'
          - '@eslint/*'
          - 'typescript-eslint'
        exclude-patterns:
          - 'eslint-plugin-qwik'
      design:
        patterns:
          - '@qwikest/icons'
          - '@fontsource/*'
      qwik:
        patterns:
          - '@builder.io/qwik'
          - '@builder.io/qwik*'
          - 'eslint-plugin-qwik'
          - 'vite-*'
          - '@vitejs/*'
          - '@rollup/plugin-*'
          - 'rollup-plugin-*'
      typescript-core:
        patterns:
          - 'typescript'
          - 'tsx'
      typescript-types:
        patterns:
          - '@types/*'
