name: Cache Nuke

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit
          disable-sudo-and-containers: true
      - run: gh cache delete --all --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
